config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations", sessions: "sessions" }
  put "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post"
  patch "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post_2"
  put "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post"
  patch "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post_2"
  put "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity"
  patch "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity_2"
  post 'bookings/:booking_id/reviews', to: "reviews#create", as: "booking_review"
  post 'bookings/:booking_id/conversations', to: "conversations#create_b", as: "booking_conversations"
  post 'users/:user_id/conversations', to: "conversations#create_u", as: "user_conversations"
  put 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review"
  patch 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review_2"
  put 'users/:id', to: "users#update", as: "user"
  patch 'users/:id', to: "users#update", as: "user_2"
  post 'offers/:offer_id/bookings', to: "bookings#create", as: 'offer_bookings'
  put 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking'
  patch 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking_2'
  post 'offers/:offer_id/conversations', to: "conversations#create", as: 'offer_conversations'
  post 'offers/:offer_id/stripe_customers', to: "stripe_customers#create", as: "offer_stripe_customers"
  put 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation"
  patch 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation_2"
  put 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation"
  patch 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation_2"
  patch 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking"
  put 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking_2"
  patch 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking"
  put 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking_2"
  scope '(:locale)', locale: /en/ do
    root to: "pages#home"
    get "/raclette", to: "pages#raclette"
    get "/legal", to: "pages#legal"
    get "/terms", to: "pages#terms"
    get "/sitemap", to:"pages#sitemap"
    get "/poster", to:"pages#poster"
    get "/early_birds_poster", to:"pages#early_birds_poster"
    get "/users/map", to: "users#map"
    get "/offers/map", to: "offers#map"
    resources :users, only: [:index, :show, :edit]
    resources :offers, except: :destroy do
      member do
        put :wish, to: "offers#wish"
        put :unwish, to: "offers#unwish"
        put :publish, to: "offers#publish"
        put :hide, to: "offers#hide"
      end
      resources :bookings, only: [:new, :edit, :show]
      resources :conversations, only: :new
      resources :stripe_customers, only: :new
    end
    resources :posts, only: [:index, :create, :update] do
      member do
        put :like, to: "posts#like"
        put :unlike, to: "posts#unlike"
      end
    end
    get 'bookings/:booking_id/reviews/new', to: "reviews#new", as: "new_booking_review"
    get 'bookings/:booking_id/conversations/new', to: "conversations#new_b", as: "new_booking_conversation"
    get 'users/:user_id/conversations/new', to: "conversations#new_u", as: "new_user_conversation"
    get 'bookings/:booking_id/reviews/:id/edit', to: "reviews#edit", as: "edit_booking_review"
    get 'reviews/:id', to: "reviews#show", as: "review"
    get "/mine", to: "offers#mine"
    get "/wishlist", to: "offers#wishlist"
    resources :conversations, only: [:index, :show]
  end
  resources :stripe_payments, only: [:new, :create]
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user1, class_name: "User"
  belongs_to :user2, class_name: "User"

  has_many :messages
  accepts_nested_attributes_for :messages
  validates_presence_of :user1, :user2

  def other_user(current_user)
    if user1 == current_user
      user2
    elsif user2 == current_user
      user1
    else
      nil
    end
  end

  def unread_messages(current_user)
    messages.select{ |message| message.writer != current_user }.select { |message| message.read_at == nil }.size
  end

  def send_new_message_email
    ConversationMailer.new_message(self).deliver
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :reply, :reply_server]
  before_action :set_offer, only: [:new, :create]
  after_action :verify_policy_scoped, :only => :index
  after_action :verify_authorized, :except => :index, unless: :devise_controller?
  respond_to :js, only: :reply
  layout "inbox", only: :show

  def index
    @conversations = policy_scope(Conversation)
  end

  def new
    @conversation = Conversation.new
    @conversation.user1 = current_user
    @conversation.user2 = @offer.user
    @message = Message.new
    authorize @conversation
  end

  def create
    @conversation = Conversation.new
    @conversation.user1 = current_user
    @conversation.user2 = @offer.user
    @message = Message.new(message_params)
    @message.writer = current_user
    @message.conversation = @conversation
    @message.save
    authorize @conversation
    if @conversation.save
      @conversation.send_new_message_email unless @conversation.user1_id == 2 || @conversation.user2_id == 2
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def new_b
    set_booking
    @conversation = Conversation.new
    @conversation.user1 = current_user
    @conversation.user2 = @booking.user
    @message = Message.new
    authorize @conversation
  end

  def create_b
    set_booking
    @conversation = Conversation.new
    @conversation.user1 = current_user
    @conversation.user2 = @booking.user
    @message = Message.new(message_params)
    @message.writer = current_user
    @message.conversation = @conversation
    @message.save
    authorize @conversation
    if @conversation.save
      @conversation.send_new_message_email unless @conversation.user1_id == 2 || @conversation.user2_id == 2
      redirect_to conversation_path(@conversation, anchor: "message-input")
    else
      render :new_b
    end
  end

  def new_u
    @conversation = Conversation.new
    @conversation.user1 = current_user
    if set_user
      @conversation.user2 = @user
    else
      @conversation.user2 = User.find(1)
    end
    @message = Message.new
    authorize @conversation
  end

  def create_u
    set_user
    @conversation = Conversation.new
    @conversation.user1 = current_user
    @conversation.user2 = @user
    @message = Message.new(message_params)
    @message.writer = current_user
    @message.conversation = @conversation
    @message.save
    authorize @conversation
    if @conversation.save
      @conversation.send_new_message_email unless @conversation.user1_id == 2 || @conversation.user2_id == 2
      redirect_to conversation_path(@conversation, anchor: "message-input")
    else
      render :new_b
    end
  end

  def show
    @conversations = current_user.conversations.sort_by{ |c| c.messages.last.created_at }.reverse
    @conversation.messages.each do |message|
      unless message.writer == current_user
        message.read_at = Time.now unless message.read_at
      end
      message.save
    end
    @message = Message.new
  end

  def reply
    @message = Message.new(message_params)
    @message.writer = current_user
    @message.conversation = @conversation
    @message.save
    @conversations = current_user.conversations.sort_by{ |c| c.messages.last.created_at }.reverse
    @conversation.send_new_message_email unless @conversation.user1_id == 2 || @conversation.user2_id == 2
  end

  def reply_server
    @message = Message.new(message_params)
    @message.writer = current_user
    @message.conversation = @conversation
    if @message.save
      @conversation.send_new_message_email unless @conversation.user1_id == 2 || @conversation.user2_id == 2
      redirect_to conversation_path(@conversation, anchor: "message-input")
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_conversation
    @conversation = Conversation.find(params[:id])
    authorize @conversation
  end

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end

  def conversation_params
    params.require(:conversation).permit(messages_attributes: [:content])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<a href="<%= conversation_path(conversation, anchor: "message-input") %>", class="conversation-preview-link">
  <div class="conversation-preview" id="<%= "conversation_#{conversation.id}" %>">
    <div class="col-xs-3 img-medium-square padding-none">
      <% if conversation.other_user(current_user).picture_file_name %>
        <%= image_tag(conversation.other_user(current_user).picture.url(:medium), { class: "img" }) %>
      <% else %>
        <%= image_tag "user_pic-225x225.png", class: "img" %>
      <% end %>
    </div>
    <div class="col-xs-7">
      <h5 class="margin-btm-5 first-name"><strong><%= conversation.other_user(current_user).first_name %></strong></h5>
      <% if conversation.user1.first_name == "Lovely Hood" %>
        <%= simple_format conversation.messages.sort_by(&:updated_at).last.content[0..4] + "..." %>
      <% else %>
        <% if conversation.messages.sort_by(&:updated_at).last.writer == current_user && conversation.messages.sort_by(&:updated_at).last.read_at %>
          <i class="fa fa-check gray-lighter"></i>&nbsp;
        <% elsif conversation.messages.sort_by(&:updated_at).last.writer == current_user %>
          <i class="fa fa-reply gray-lighter"></i>&nbsp;
        <% end %>
        <%= conversation.messages.sort_by(&:updated_at).last.content.size >= 20 ? conversation.messages.sort_by(&:updated_at).last.content[0..19] + "..." : conversation.messages.sort_by(&:updated_at).last.content %>
      <% end %>
    </div>
    <div class="col-xs-2 margin-top-10 padding-none">
      <p class="small gray-lighter text-right margin-top-14"><%= conversation.messages.sort_by(&:updated_at).last.created_at.strftime("%e %b") %></p>
    </div>
  </div>
</a>

app/views/conversations/_conversation_with_unread_messages.html.erb
<a href="<%= conversation_path(conversation, anchor: "message-input") %>", class="conversation-preview-link">
  <div class="conversation-preview unread-messages"  id="<%= "conversation_#{conversation.id}" %>">
    <div class="col-xs-3 img-medium-square padding-none">
      <% if conversation.other_user(current_user).picture_file_name %>
        <%= image_tag(conversation.other_user(current_user).picture.url(:medium), { class: "img" }) %>
      <% else %>
        <%= image_tag "user_pic-225x225.png", class: "img" %>
      <% end %>
    </div>
    <div class="col-xs-7">
      <h5 class="margin-btm-5 first-name"><strong><%= conversation.other_user(current_user).first_name %></strong></h5>
      <% if conversation.user1.first_name == "Lovely Hood" %>
        <%= simple_format conversation.messages.sort_by(&:updated_at).last.content[0..4] + "..." %>
      <% else %>
        <% if conversation.messages.sort_by(&:updated_at).last.writer == current_user && conversation.messages.sort_by(&:updated_at).last.read_at %>
          <i class="fa fa-check gray-lighter"></i>&nbsp;
        <% elsif conversation.messages.sort_by(&:updated_at).last.writer == current_user %>
          <i class="fa fa-reply gray-lighter"></i>&nbsp;
        <% end %>
        <%= simple_format(conversation.messages.sort_by(&:updated_at).last.content.size >= 20 ? conversation.messages.sort_by(&:updated_at).last.content[0..19] + "..." : conversation.messages.sort_by(&:updated_at).last.content) %>
      <% end %>
    </div>
    <div class="col-xs-2 margin-top-10 text-right">
      <span class="badge small-badge margin-top-18">
      </span>
    </div>
  </div>
</a>

app/views/conversations/_form.html.erb
<% if current_user.conversation_with(@offer.user) %>
  <%= form_for([current_user.conversation_with(@offer.user), @message], method: :put, url: reply_server_conversation_path(current_user.conversation_with(@offer.user))) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>
    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= form_for([@offer, @conversation, @message], method: :post, url: offer_conversations_path(@offer)) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>
    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/conversations/_form_b.html.erb
<% if current_user.conversation_with(@booking.offer.user) %>
  <%= form_for([current_user.conversation_with(@booking.offer.user), @message], method: :put, url: reply_server_conversation_path(current_user.conversation_with(@booking.offer.user))) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>

    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= form_for([@booking, @conversation, @message], method: :post, url:   booking_conversations_path(@booking)) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>

    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/conversations/_form_u.html.erb
<% if current_user.conversation_with(@user) %>
  <%= form_for([current_user.conversation_with(@user), @message], method: :put, url: reply_server_conversation_path(current_user.conversation_with(@user))) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>

    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= form_for([@user, @conversation, @message], method: :post, url: user_conversations_path(@user)) do |f| %>
    <div class="form-group">
      <div class="col-xs-12">
        <%= f.text_area :content, rows: 4, class: "form-control" %>
      </div>
    </div>

    <div class="form-group margin-btm-none">
      <div class="col-xs-12">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/conversations/_message.html.erb
<div class="stick-down-target message white-bg col-xs-12">
  <div class="message-date">
    <span class="white-bg padding-sides-5"><%= l(message.created_at, format: "%A %e %B - %lh%M").capitalize %></span>
  </div>
  <div class="message-content margin-top-10">
    <div class="col-xs-3 img-small-square padding-none">
      <% if message.writer.picture_file_name %>
        <%= image_tag(message.writer.picture.url(:medium), { class: "img" }) %>
      <% else %>
        <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
      <% end %>
    </div>
    <div class="col-xs-9 padding-left-10">
      <h5 class="margin-none"><%= link_to message.writer.first_name, user_path(message.writer), class: "nice-link" %></h5><p class=""><%= simple_format message.content %></p>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-default margin-top-15 padding-none white-bg">
        <div class="panel-heading">
          <h3><%= t('.inbox') %></h3>
        </div>
        <div class="panel-body padding-none">
          <% current_user.conversations.sort_by { |c| c.messages.last.updated_at }.reverse.each do |conversation| %>
            <% if conversation.messages.select{ |message| message.writer != current_user }.map { |message| message.read_at }.include? nil %>
              <%= render "conversation_with_unread_messages", conversation: conversation %>
            <% else %>
              <%= render "conversation", conversation: conversation %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-default margin-top-15 padding-none">
        <div class="panel-heading">
          <h3><%= t('.contact_owner', offer: @offer.nature) %></h3>
        </div>
        <div class="panel-body form-horizontal">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/new_b.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-default margin-top-15 padding-none">
        <div class="panel-heading">
          <h3><%= t('.contact_owner', first_name: @booking.user.first_name) %></h3>
        </div>
        <div class="panel-body form-horizontal">
          <%= render "form_b" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/new_u.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-default margin-top-15 padding-none">
        <div class="panel-heading">
          <h3><%= t('.contact_owner', first_name: @user.first_name) %></h3>
        </div>
        <div class="panel-body form-horizontal">
          <%= render "form_u" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<%= content_for(:title) do %>
  <%= t('.title', number: current_user.unread_conversations > 0 ? "(" + current_user.unread_conversations.to_s + ") " : "") %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row prerender">
    <div class="col-md-4 inbox">
      <div class="panel panel-default margin-top-15 padding-none white-bg" id="panel-inbox">
        <div class="panel-heading border-btm-light">
          <h4><%= t('.inbox') %></h4>
        </div>
        <div class="panel-body padding-none panel-body-inbox" id="conversations">
          <div class="loader"> </div>
        </div>
      </div>
    </div>
    <div class="col-md-8 conversation">
      <div class="panel panel-default margin-top-15 padding-none" id="panel-conversation">
        <div class="panel-heading border-btm-light">
          <h4 id="first-name">
            <% if @conversation.user1 == current_user %>
              <%= @conversation.user2.first_name %>
            <% else %>
              <%= @conversation.user1.first_name %>
            <% end %>
          </h4>
        </div>
        <div class="panel-body panel-body-conversation padding-none">
          <div id="messages">
            <div class="loader"> </div>
          </div>
          <div id="new_message">
            <div class="stick-down-target reply" >
              <div class="form-group margin-btm-10">
                <textarea class="form-control" id="message-input"></textarea>
              </div>
              <div class="form-group margin-btm-none text-right">
                <button class="btn btn-post"><%= t('.submit', default: 'Envoyer') %></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= react_component "Inbox",
    render(template: 'conversations/show.json.jbuilder') %>
</div>
<%= content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function(e) {
      $('.prerender').remove()
      togglePaddingAndBorder();
      $(window).on('resize', function() {
        togglePaddingAndBorder();
      })
      $('#messages-nav-link').addClass("hover");
      $("#messages").niceScroll({
        cursorwidth: "10px",
        cursorcolor: "#ddd",
        cursoropacitymin: 1,
        background: "#f8f8f8",
        cursorborder: "1px solid #fff",
      });
      $(".panel-body-inbox").niceScroll({
        cursorwidth: "10px",
        cursorcolor: "#ddd",
        cursoropacitymin: 1,
        background: "#f8f8f8",
        cursorborder: "1px solid #fff"
      });
      $('#messages').scrollTop($('#messages')[0].scrollHeight);
      $('#message-input').focus()
    });
  <% end %>
<% end %>