config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations", sessions: "sessions" }
  put "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post"
  patch "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post_2"
  put "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post"
  patch "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post_2"
  put "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity"
  patch "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity_2"
  post 'bookings/:booking_id/reviews', to: "reviews#create", as: "booking_review"
  post 'bookings/:booking_id/conversations', to: "conversations#create_b", as: "booking_conversations"
  post 'users/:user_id/conversations', to: "conversations#create_u", as: "user_conversations"
  put 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review"
  patch 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review_2"
  put 'users/:id', to: "users#update", as: "user"
  patch 'users/:id', to: "users#update", as: "user_2"
  post 'offers/:offer_id/bookings', to: "bookings#create", as: 'offer_bookings'
  put 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking'
  patch 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking_2'
  post 'offers/:offer_id/conversations', to: "conversations#create", as: 'offer_conversations'
  post 'offers/:offer_id/stripe_customers', to: "stripe_customers#create", as: "offer_stripe_customers"
  put 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation"
  patch 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation_2"
  put 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation"
  patch 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation_2"
  patch 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking"
  put 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking_2"
  patch 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking"
  put 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking_2"
  scope '(:locale)', locale: /en/ do
    root to: "pages#home"
    get "/raclette", to: "pages#raclette"
    get "/legal", to: "pages#legal"
    get "/terms", to: "pages#terms"
    get "/sitemap", to:"pages#sitemap"
    get "/poster", to:"pages#poster"
    get "/early_birds_poster", to:"pages#early_birds_poster"
    get "/users/map", to: "users#map"
    get "/offers/map", to: "offers#map"
    resources :users, only: [:index, :show, :edit]
    resources :offers, except: :destroy do
      member do
        put :wish, to: "offers#wish"
        put :unwish, to: "offers#unwish"
        put :publish, to: "offers#publish"
        put :hide, to: "offers#hide"
      end
      resources :bookings, only: [:new, :edit, :show]
      resources :conversations, only: :new
      resources :stripe_customers, only: :new
    end
    resources :posts, only: [:index, :create, :update] do
      member do
        put :like, to: "posts#like"
        put :unlike, to: "posts#unlike"
      end
    end
    get 'bookings/:booking_id/reviews/new', to: "reviews#new", as: "new_booking_review"
    get 'bookings/:booking_id/conversations/new', to: "conversations#new_b", as: "new_booking_conversation"
    get 'users/:user_id/conversations/new', to: "conversations#new_u", as: "new_user_conversation"
    get 'bookings/:booking_id/reviews/:id/edit', to: "reviews#edit", as: "edit_booking_review"
    get 'reviews/:id', to: "reviews#show", as: "review"
    get "/mine", to: "offers#mine"
    get "/wishlist", to: "offers#wishlist"
    resources :conversations, only: [:index, :show]
  end
  resources :stripe_payments, only: [:new, :create]
end

app/views/shared/_contact_client.html.erb
<div class="panel panel-default padding-none">
  <div class="panel-heading">
    <h4><%= t('.contact_info') %></h4>
  </div>
  <div class="panel-body">
    <div class="contact">
      <div class="row">
        <div class="col-xs-2 text-center">
          <%= link_to user_path(booking.user) do %>
            <div class="img-review-box">
              <div class="img-medium">
                <% if booking.user.picture_file_name %>
                  <%= image_tag(booking.user.picture.url(:medium), { class: "img" }) %>
                <% else %>
                  <%= image_tag "user_pic-60.png" %>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="user-name">
            <%= link_to booking.user.first_name, user_path(booking.user), class: "link-unstyled" %>
          </div>
        </div>
        <div class="col-xs-10">
          <div class="contact-content">
            <div class="row">
              <div class="col-xs-12">
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-star-o"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <% if booking.user.cto_reviews.size.to_i >= 1 %>
                      <%= link_to(user_path(booking.user, anchor: "#comments"), {class: "link-unstyled"}) do %>
                        <% booking.user.avge_cto_rating.round.times do %>
                          <i class="fa fa-star small-star-gold"></i>
                        <% end %>
                        <% (5 - booking.user.avge_cto_rating.round).times do %>
                          <i class="fa fa-star small-star"></i>
                        <% end %>
                        (<%= booking.user.avge_cto_rating.round(1) %>/5 - <%= pluralize(booking.user.cto_reviews.size, t('.comment')) + t('.as_a_client') %> - <%= booking.user.avge_cto_reco_percent.round %>% <%= t('.of_recos') %>)
                      <% end %>
                    <% else %>
                      <%= t('.no_comment_yet') + t('.as_a_client') %>
                    <% end %>
                  </div>
                </p>
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-star"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <% if booking.user.otc_reviews.size.to_i >= 1 %>
                      <%= link_to(user_path(booking.user, anchor: "#comments"), {class: "link-unstyled"}) do %>
                        <% booking.user.avge_otc_rating.round.times do %>
                          <i class="fa fa-star small-star-gold"></i>
                        <% end %>
                        <% (5 - booking.user.avge_otc_rating.round).times do %>
                          <i class="fa fa-star small-star"></i>
                        <% end %>
                        (<%= booking.user.avge_otc_rating.round(1) %>/5 - <%= pluralize(booking.user.otc_reviews.size, t('.comment')) + t('.as_owner') %> - <%= booking.user.avge_otc_reco_percent.round %>% <%= t('.of_recos') %>)
                      <% end %>
                    <% else %>
                      <%= t('.no_comment_yet') + t('.as_owner') %>
                    <% end %>
                  </div>
                </p>
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-map-marker"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <%= booking.user.address %>
                  </div>
                </p>
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-send"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <%= t('.send_a') %> <%= link_to t('.message'), new_booking_conversation_path(booking) %>
                  </div>
                </p>
              </div>
            </div>
            <div class="review-footer">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_contact_owner.html.erb
<div class="panel panel-default padding-none">
  <div class="panel-heading">
    <h4><%= t('.contact_info') %></h4>
  </div>
  <div class="panel-body">
    <div class="contact">
      <div class="row">
        <div class="col-xs-2 text-center">
          <%= link_to user_path(booking.offer.user) do %>
            <div class="img-review-box">
              <div class="img-medium">
                <% if booking.offer.user.picture_file_name %>
                  <%= image_tag(booking.offer.user.picture.url(:medium), { class: "img" }) %>
                <% else %>
                  <%= image_tag "user_pic-60.png" %>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="user-name">
            <%= link_to booking.offer.user.first_name, user_path(booking.offer.user), class: "link-unstyled" %>
          </div>
        </div>
        <div class="col-xs-10">
          <div class="contact-content">
            <div class="row">
              <div class="col-xs-12">
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-map-marker"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <%= booking.offer.user.address %>
                  </div>
                </p>
                <p>
                  <div class="col-xs-1 text-center padding-none">
                    <i class="fa fa-send"></i>
                  </div>
                  <div class="col-xs-11 padding-none">
                    <%= t('.send_a') %> <%= link_to t(".message"), new_user_conversation_path(booking.offer.user) %>
                  </div>
                </p>
                <% unless booking.offer.user.phone == "" %>
                  <p>
                    <div class="col-xs-1 text-center padding-none">
                      <i class="fa fa-phone"></i>
                    </div>
                    <div class="col-xs-11 padding-none">
                      <%= t('.phone') %> <%= booking.offer.user.phone %>
                    </div>
                  </p>
                <% end %>
              </div>
            </div>
            <div class="review-footer">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ongoing_bookings.html.erb
<div class="booking">
  <div class="row">
    <div class="col-xs-2 text-center">
      <div class="img-nature-box">
        <%= link_to offer_path(booking.offer), class: "link-unstyled" do %>
          <% if booking.offer.type_of_offer == "sell" %>
            <%= image_tag "sell.png", width: "60" %>
          <% else %>
            <%= image_tag "#{booking.offer.nature}.png", width: "60" %>
          <% end %>
      </div>
      <div class="user-name hidden-xs">
          <%= booking.offer.i18n_nature(params[:locale]) %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-10">
      <div class="booking-content">
        <div class="row">
          <div class="col-xs-12">
            <% if booking.offer.type_of_offer == "rent" %>
              <p>
                <% if booking.start_date == Date.today %>
                   <%= booking.end_date.strftime("%d %b") %>.
                <% else %>
                  <%= t('.since') %> <strong><%= pluralize((Date.today - booking.start_date).to_i, t(".day")) %></strong> <%= t('.and_until') %> <%= booking.end_date.strftime("%d %b") %>.
                <% end %>
              </p>
            <% elsif booking.offer.type_of_offer == "service" %>
              <p>
                <% if booking.start_date == Date.today %>
                  <%= t('.since_today') %> <%= booking.end_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.end_hour.strftime("%H:%M") %>.
                <% else %>
                  <%= t('.since') %> <strong><%= pluralize((Date.today - booking.start_date).to_i, t(".day")) %></strong> <%= t('.and_until') %> <%= booking.end_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.end_hour.strftime("%H:%M") %>.
                <% end %>
              </p>
            <% end %>
            <% if current_user == booking.offer.user %>
              <p><%= t('.you_will_earn') %> <%= (booking.booking_price * 0.96).round %><%= t('.currency') %>.</p>
            <% end %>
          </div>
        </div>
        <br>
        <div class="booking-footer">
          <div class="booking-date hidden-xs">
            <%= l(booking.created_at, format: "%B %Y") %>
          </div>
          <div class="user-link">
            <% if booking.offer.user == current_user %>
              <%= link_to user_path(booking.user) do %>
                <table class="user-assets list-inline list-unstyled margin-none">
                  <td>
                    <%= booking.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.user.picture_file_name %>
                        <%= image_tag(booking.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% else %>
              <%= link_to user_path(booking.offer.user) do %>
                <table class="user-assets list-inline list-unstyled margin-none">
                  <td>
                    <%= booking.offer.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.offer.user.picture_file_name %>
                        <%= image_tag(booking.offer.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_passed_bookings.html.erb
<div class="booking", id="<%= "booking_#{booking.id}" %>">
  <div class="row">
    <div class="col-xs-2 text-center">
      <div class="img-nature-box">
        <%= link_to offer_path(booking.offer), class: "link-unstyled" do %>
          <% if booking.offer.type_of_offer == "sell" %>
            <%= image_tag "sell.png", width: "60" %>
          <% else %>
            <%= image_tag "#{booking.offer.nature}.png", width: "60" %>
          <% end %>
      </div>
      <div class="user-name hidden-xs">
          <%= booking.offer.i18n_nature(params[:locale]) %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-10">
      <div class="booking-content">
        <div class="row">
          <div class="col-xs-12">
            <% if booking.offer.type_of_offer == "sell" %>
              <% if booking.offer.sold.nil? && booking.cancelled.nil? %>
                <% if current_user == booking.user %>
                  <p>
                    <% if booking.start_date == Date.today %>
                      <strong><%= t('.today') %></strong>
                    <% else %>
                      <%= t('.time_ago', days: pluralize((Date.today - booking.start_date).to_i, t('.day'))) %>
                    <% end %>
                    (<%= booking.start_date.strftime("%d %b") %>).
                  </p>
                  <p>
                    <ul class="confirmation list-unstyle list-inline">
                      <li>
                        <%= t('.buy') %> <%= link_to booking.offer.i18n_nature(params[:locale]),  offer_path(booking.offer) %>
                      </li>
                      <li class="confirmation-thumbs">
                        <%= form_for booking, url: buy_booking_path(booking) do |f| %>
                          <%= button_tag(type: 'submit', class: "btn btn-success btn-margin btn-wide btn-circle") do %>
                            <i class="fa fa-check"></i>
                          <% end %>
                        <% end %>
                      </li>
                      <li class="confirmation-thumbs">
                        <%= form_for booking, method: :put, url: cancel_booking_path(booking) do |f| %>
                          <%= f.hidden_field :cancelled, value: true %>
                          <%= button_tag(type: 'submit', class: "btn btn-danger btn-margin btn-wide btn-circle") do %>
                            <i class="fa fa-close"></i>
                          <% end %>
                        <% end %>
                      </li>
                    </ul>
                  </p>
                <% else %>
                  <p>
                    <%= t('.pending_decision', name: booking.user.first_name) %>.
                  </p>
                <% end %>
              <% elsif booking.offer.sold %>
                <% if current_user == booking.offer.user %>
                  <p>
                    <% if booking.start_date == Date.today %>
                      <strong><%= t('.today') %></strong>
                    <% else %>
                      <%= t('.time_ago', days: pluralize((Date.today - booking.start_date).to_i, t(".day"))) %>
                    <% end %>
                    (le <%= booking.start_date.strftime("%d %b") %>).
                  </p>
                  <p>
                    <%= t('.leave_a_review') %> <%= link_to t('.comment'), new_booking_review_path(booking) %> <%= t('.to') %> <%= booking.user.first_name %>.
                  </p>
                <% end %>
              <% end %>
            <% elsif booking.offer.type_of_offer == "rent" %>
              <p>
                <% if booking.end_date == Date.today %>
                  <strong><%= t('.today') %></strong>
                <% else %>
                  <%= t('.time_ago', days: pluralize((Date.today - booking.end_date).to_i, t('.day'))) %>
                <% end %>
                (<%= booking.start_date.strftime("%d %b") %> - <%= booking.end_date.strftime("%d %b") %>).
              </p>
              <p>
                <% if current_user == booking.user %>
                  <%= t('.leave_a_review') %> <%= link_to t('.comment'), new_booking_review_path(booking) %> <%= t('.to') %> <%= booking.offer.user.first_name %>.
                <% elsif current_user == booking.offer.user %>
                  <%= t('.leave_a_review') %> <%= link_to t('.comment'), new_booking_review_path(booking) %> <%= t('.to') %> <%= booking.user.first_name %>.
                <% end %>
              </p>
            <% elsif booking.offer.type_of_offer == "service" %>
              <p>
                <% if booking.end_date == Date.today %>
                  <strong><%= t('.today') %></strong>
                <% else %>
                  <%= t('.time_ago', days: pluralize((Date.today - booking.end_date).to_i, t('.day'))) %>
                <% end %>
                (<%= booking.start_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.start_hour.strftime("%H:%M") %> - <%= booking.end_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.end_hour.strftime("%H:%M") %>).
              </p>
              <p>
                <%= t('.leave_a_review') %> <%= link_to t('.comment'), new_booking_review_path(booking) %> <%= t('.to') %> <%= current_user == booking.user ? booking.offer.user.first_name : booking.user.first_name %>.
              </p>
            <% end %>
          </div>
        </div>
        <br>
        <div class="booking-footer">
          <div class="booking-date hidden-xs">
            <%= l(booking.created_at, format: "%B %Y") %>
          </div>
          <div class="user-link">
            <% if booking.offer.user == current_user %>
              <%= link_to user_path(booking.user) do %>
                <table class="user-assets margin-none">
                  <td>
                    <%= booking.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.user.picture_file_name %>
                        <%= image_tag(booking.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% else %>
              <%= link_to user_path(booking.offer.user) do %>
                <table class="user-assets margin-none">
                  <td>
                    <%= booking.offer.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.offer.user.picture_file_name %>
                        <%= image_tag(booking.offer.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<div class="review" id="<%= "review_#{review.id}" %>">
  <div class="row">
    <div class="col-xs-2 text-center">
      <% if review.review_type == "cto" %>
        <%= link_to user_path(booking.user) do %>
          <div class="img-review-box">
            <div class="img-medium">
              <% if booking.user.picture_file_name %>
                <%= image_tag(booking.user.picture.url(:medium), { class: "img-60" }) %>
              <% else %>
                <%= image_tag "user_pic-60.png", class: 'img-60' %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="user-name hidden-xs">
          <%= link_to booking.user.first_name, user_path(booking.user), class: "link-unstyled" %>
        </div>
      <% elsif review.review_type == "otc" %>
        <%= link_to user_path(booking.offer.user) do %>
          <div class="img-review-box">
            <div class="img-medium">
              <% if booking.offer.user.picture_file_name %>
                <%= image_tag(booking.offer.user.picture.url(:medium), { class: "img-60" }) %>
              <% else %>
                <%= image_tag "user_pic-60.png", class: 'img-60' %>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="user-name hidden-xs">
          <%= link_to booking.offer.user.first_name, user_path(booking.offer.user), class: "link-unstyled" %>
        </div>
      <% end %>
    </div>
    <div class="col-xs-10">
      <div class="review-content">
        <div class="row">
          <div class="col-xs-12 comment">
            <%= simple_format review.comment %>
          </div>
        </div>
        <div class="review-footer">
          <div class="review-date hidden-xs">
            <%= l(review.created_at, format: "%B %Y") %>
          </div>
          <div class="offer-link">
            <%= link_to offer_path(booking.offer) do %>
            <table>
              <td>
                <%= booking.offer.i18n_nature(params[:locale]) %>
              </td>
              <td>&nbsp;&nbsp;</td>
              <td>
                <% if booking.offer.picture_file_name %>
                  <%= image_tag(booking.offer.picture.url(:medium), { class: "img-20" }) %>
                <% else %>
                  <%= image_tag "no-image-38.png", class: "img-20" %>
                <% end %>
              </td>
            </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_upcoming_bookings.html.erb
<div class="booking">
  <div class="row">
    <div class="col-xs-2 text-center">
      <div class="img-nature-box">
        <%= link_to offer_path(booking.offer), class: "link-unstyled" do %>
          <% if booking.offer.type_of_offer == "sell" %>
            <%= image_tag "sell.png", width: "60" %>
          <% else %>
            <%= image_tag "#{booking.offer.nature}.png", width: "60" %>
          <% end %>
      </div>
      <div class="user-name hidden-xs">
          <%= booking.offer.nature %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-10">
      <div class="booking-content">
        <div class="row">
          <div class="col-xs-12">
            <!-- si c'est un objet à louer, on display les dates -->
            <% if booking.offer.type_of_offer == "rent" %>
              <p>
                <% if booking.start_date == Date.today %>
                  <strong><%= t('.today') %></strong>
                <% else %>
                  <%= t('.in') %> <strong><%= pluralize((booking.start_date - Date.today).to_i, t('.day')) %></strong>
                <% end %>
                (<%= booking.start_date.strftime("%d %b") %> - <%= booking.end_date.strftime("%d %b") %>).
              </p>
            <!-- si c'est un service, on display les dates + heures -->
            <% elsif booking.offer.type_of_offer == "service" %>
              <p>
                <% if booking.start_date == Date.today %>
                  <strong><%= t('.today') %></strong>
                <% else %>
                  <%= t('.in') %> <strong><%= pluralize((booking.start_date - Date.today).to_i, t('.day')) %></strong>
                <% end %>
                (<%= booking.start_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.start_hour.strftime("%H:%M") %> - <%= booking.end_date.strftime("%d %b") %> <%= t('.at') %> <%= booking.end_hour.strftime("%H:%M") %>).
              </p>
            <!-- si c'est une vente, on display la date de rdv -->
            <% else %>
              <p><strong><%= t('.rdv') %></strong> <%= booking.start_date.strftime("%d %b") %>.</p>
            <% end %>
            <% if current_user == booking.user %>
              <p>
                <% if booking.accepted && booking.offer.type_of_offer == "service" %>
                  <%= t('.booking_accepted') %> <%= t('.by') %> <%= booking.offer.user.first_name %>.
                <% elsif booking.accepted %>
                  <%= t('.booking_accepted') %>. <%= t('.check') %> <%= link_to t('.route'), offer_booking_path(booking.offer, booking, anchor: "map") %> <%= t('.to') %> <%= booking.offer.user.first_name %><%= t('.apostrophe_s') %>.
                <% else %>
                 <%= t('.waiting_for') %> <%= booking.offer.user.first_name %>
                <% end %>
               </p>
            <% else %>
              <p>
                <% if booking.accepted && booking.offer.type_of_offer == "service" %>
                  <%= t('.booking_accepted') %>. <%= t('.check') %> <%= link_to t('.route'), offer_booking_path(booking.offer, booking, anchor: "map") %> <%= t('.to') %> <%= booking.user.first_name %><%= t('.apostrophe_s') %>.
                <% elsif booking.accepted && booking.offer.type_of_offer == "sell" %>
                  <%= t('.you_may_earn') %> <%= (booking.booking_price * 0.96).round %><%= t('.currency') %>.
                <% elsif booking.accepted %>
                  <%= t('.you_will_earn') %> <%= (booking.booking_price * 0.96).round %><%= t('.currency') %>.
                <% else %>
                  <%= t('.unanswered_request') %> <%= booking.user.first_name %><%= t('.request') %>. <%= link_to t('.reply'), edit_offer_booking_path(booking.offer, booking) %>
                <% end %>
              </p>
            <% end %>
          </div>
        </div>
        <br>
        <div class="booking-footer">
          <div class="booking-date hidden-xs">
            <%= l(booking.created_at, format: "%B %Y") %>
          </div>
          <div class="user-link">
            <% if booking.offer.user == current_user %>
              <%= link_to user_path(booking.user) do %>
                <table class="user-assets margin-none">
                  <td>
                    <%= booking.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.user.picture_file_name %>
                        <%= image_tag(booking.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% else %>
              <%= link_to user_path(booking.offer.user) do %>
                <table class="user-assets margin-none">
                  <td>
                    <%= booking.offer.user.first_name %>
                  </td>
                  <td>&nbsp;&nbsp;</td>
                  <td>
                    <div class="img-mini">
                      <% if booking.offer.user.picture_file_name %>
                        <%= image_tag(booking.offer.user.picture.url(:medium), { class: "img-20" }) %>
                      <% else %>
                        <%= image_tag "user_pic-38.png", class: "img-20" %>
                      <% end %>
                    </div>
                  </td>
                </table>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>