config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations", sessions: "sessions" }
  put "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post"
  patch "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post_2"
  put "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post"
  patch "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post_2"
  put "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity"
  patch "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity_2"
  post 'bookings/:booking_id/reviews', to: "reviews#create", as: "booking_review"
  post 'bookings/:booking_id/conversations', to: "conversations#create_b", as: "booking_conversations"
  post 'users/:user_id/conversations', to: "conversations#create_u", as: "user_conversations"
  put 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review"
  patch 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review_2"
  put 'users/:id', to: "users#update", as: "user"
  patch 'users/:id', to: "users#update", as: "user_2"
  post 'offers/:offer_id/bookings', to: "bookings#create", as: 'offer_bookings'
  put 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking'
  patch 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking_2'
  post 'offers/:offer_id/conversations', to: "conversations#create", as: 'offer_conversations'
  post 'offers/:offer_id/stripe_customers', to: "stripe_customers#create", as: "offer_stripe_customers"
  put 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation"
  patch 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation_2"
  put 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation"
  patch 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation_2"
  patch 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking"
  put 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking_2"
  patch 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking"
  put 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking_2"
  scope '(:locale)', locale: /en/ do
    root to: "pages#home"
    get "/raclette", to: "pages#raclette"
    get "/legal", to: "pages#legal"
    get "/terms", to: "pages#terms"
    get "/sitemap", to:"pages#sitemap"
    get "/poster", to:"pages#poster"
    get "/early_birds_poster", to:"pages#early_birds_poster"
    get "/users/map", to: "users#map"
    get "/offers/map", to: "offers#map"
    resources :users, only: [:index, :show, :edit]
    resources :offers, except: :destroy do
      member do
        put :wish, to: "offers#wish"
        put :unwish, to: "offers#unwish"
        put :publish, to: "offers#publish"
        put :hide, to: "offers#hide"
      end
      resources :bookings, only: [:new, :edit, :show]
      resources :conversations, only: :new
      resources :stripe_customers, only: :new
    end
    resources :posts, only: [:index, :create, :update] do
      member do
        put :like, to: "posts#like"
        put :unlike, to: "posts#unlike"
      end
    end
    get 'bookings/:booking_id/reviews/new', to: "reviews#new", as: "new_booking_review"
    get 'bookings/:booking_id/conversations/new', to: "conversations#new_b", as: "new_booking_conversation"
    get 'users/:user_id/conversations/new', to: "conversations#new_u", as: "new_user_conversation"
    get 'bookings/:booking_id/reviews/:id/edit', to: "reviews#edit", as: "edit_booking_review"
    get 'reviews/:id', to: "reviews#show", as: "review"
    get "/mine", to: "offers#mine"
    get "/wishlist", to: "offers#wishlist"
    resources :conversations, only: [:index, :show]
  end
  resources :stripe_payments, only: [:new, :create]
end

app/models/offer.rb
module PublicActivity
  module ORM
    module ActiveRecord
      class Activity < ::ActiveRecord::Base
        acts_as_votable
        has_many :activity_comments
      end
    end
  end
end
class Offer < ActiveRecord::Base
  include PublicActivity::Common
  # tracked only: :create, owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user

  has_many :bookings
  has_attached_file :picture,
    styles: { large: "600x600#", medium: "300x300#", thumb: "100x100#", original: "600x600>" }

  acts_as_votable

  validates_presence_of :user, :nature, :type_of_offer, :description
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  include AlgoliaSearch

  algoliasearch if: :published, index_name: "#{self}#{ENV['ALGOLIA_SUFFIX']}" do
    # associated index settings can be configured from here

    attributesToIndex ['nature', 'nature_en', 'description']

    attributesForFaceting [ 'type_of_offer' ]

    add_attribute :_geoloc do
      { lat: user.latitude, lng: user.longitude }
    end

    add_attribute :one_price_int do
      one_price_int
    end

    add_attribute :one_price do
      one_price_int
    end

    add_attribute :picture_url do
      picture.url(:medium)
    end

    add_attribute :large_picture_url do
      picture.url(:large)
    end

    add_attribute :original_picture_url do
      picture.url(:original)
    end

    add_attribute :free? do
      free?
    end

    add_attribute :nature_en do
      nature_en
    end

    add_attribute :picture? do
      if picture.url(:medium) == "/pictures/medium/missing.png"
        nil
      else
        true
      end
    end

    add_attribute :icon_img do
      if type_of_offer == "sell"
        '<img src="../assets/sell.png" width="32" />'
      else
        '<img src="../assets/' + nature + '.png" width="32" />'
      end
    end
  end

  def i18n_nature(locale)
    if type_of_offer == "sell"
      nature
    elsif locale == "en"
      NATURES[:en][type_of_offer.to_sym][NATURES[type_of_offer.to_sym].index(nature)]
    else
      nature
    end
  end

  def nature_en
    if type_of_offer == "sell"
      nature
    else
      NATURES[:en][type_of_offer.to_sym][NATURES[type_of_offer.to_sym].index(nature)]
    end
  end

  def one_price(trad_h, trad_w, trad_d)
    output = nil
    if type_of_offer == "service"
      if hourly_price
        output = "#{hourly_price}#{trad_h}"
      end
    elsif type_of_offer == "rent"
      if weekly_price
        output = "#{weekly_price}#{trad_w}"
      end
      if daily_price
        output = "#{daily_price}#{trad_d}"
      end
    else
      if price
        output = "#{price}€"
      end
    end
    output
  end

  def one_price_int
    output = nil
    if type_of_offer == "service"
      if hourly_price
        output = hourly_price
      end
    elsif type_of_offer == "rent"
      if weekly_price
        output = weekly_price
      end
      if daily_price
        output = daily_price
      end
    else
      if price
        output = price
      end
    end
    output
  end

  def free?
    one_price_int == 0 ? true : false
  end

  def available?(first_day, last_day)
    output = true
    if self.bookings
      self.bookings.each do |booking|
        if ((booking.start_date..booking.end_date).include? first_day) || ((booking.start_date..booking.end_date).include? last_day)
          output = false
          break
        end
      end
    end
    output
  end

  def cto_reviews
    bookings.map { |booking| booking.reviews.select { |review| review.review_type == "cto" } }.flatten.sort_by { |review| review.created_at }.reverse
  end

  def average_score
    score = 0
    cto_reviews.each do |review|
      score += review.cto_score
    end
    score.fdiv(cto_reviews.size)
  end

  def communication_score
    score = 0
    cto_reviews.each do |review|
      score += review.communication_rating
    end
    score.fdiv(cto_reviews.size)
  end

  def punctuality_score
    score = 0
    cto_reviews.each do |review|
      score += review.punctuality_rating
    end
    score = score.fdiv(cto_reviews.size)
  end

  def quality_price_score
    score = 0
    cto_reviews.each do |review|
      score += review.quality_price_rating
    end
    score = score.fdiv(cto_reviews.size)
  end

  def otc_reviews
    bookings.map { |booking| booking.reviews.select { |review| review.review_type == "otc" } }.flatten
  end

  def send_new_offer_email
    OfferMailer.new_offer(self).deliver
  end

end

app/controllers/offers_controller.rb
require 'rails_autolink'
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :wish, :unwish, :publish, :hide]
  after_action :verify_policy_scoped, :only => [:index]
  after_action :verify_authorized, :except => [:index, :wishlist], unless: :devise_controller?
  layout 'map', only: [:index, :map]

  def index
    if current_user.latitude.nil?
      redirect_to edit_user_path(current_user)
      flash.keep[:alert] = t(".complete_profile")
    end
    @offers = policy_scope(Offer)
  end

  def mine
    @class = 'mine'
    @offers = current_user.offers
    # flash.now[:alert] = t(".dbl_click")
    authorize @offers
  end

  def new
    @offer = current_user.offers.new
    authorize @offer
    if current_user.latitude.nil?
      redirect_to edit_user_path(current_user)
      flash.keep[:alert] = t(".complete_profile")
    end
    if params[:locale]
      @natures = NATURES[params[:locale].to_sym]
    else
      @natures = NATURES
    end
  end

  def create
    @offer = current_user.offers.new(offer_params)
    authorize @offer
    @offer.published = true
    if @offer.type_of_offer == "sell"
      @offer.sell = true
    end
    if params[:locale]
      @natures = NATURES[params[:locale].to_sym]
    else
      @natures = NATURES
    end
    if @offer.type_of_offer == "rent" || @offer.type_of_offer == "sell"
      if NATURES[:en][:rent].index(@offer.nature)
        @offer.nature = NATURES[:rent][NATURES[:en][:rent].index(@offer.nature)]
      end
      test_offer_info_and_redirect
    end
    if @offer.type_of_offer == "service"
      if NATURES[:en][:service].index(@offer.nature)
        @offer.nature = NATURES[:service][index(NATURES[:en][:service].index(@offer.nature))]
      end
      test_offer_info_and_redirect
    end
  end

  def edit
    if params[:locale]
      @natures = NATURES[params[:locale].to_sym]
    else
      @natures = NATURES
    end
  end

  def update
    if @offer.update(offer_params)
      if @offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price'))
        respond_to do |format|
          format.html { redirect_to offer_path(@offer) }
          format.js { flash.now[:notice] = t('.successfully_published', default: "Votre annonce %{offer} est désormais %{state}", offer: @offer.i18n_nature(params[:locale]), state: @offer.published ? t('.visible') : t('.hidden') ) }
        end
      else
        flash.now[:alert] = "Merci de renseigner un prix"
        render :edit
      end
    else
      render :edit
    end
  end

  def publish
    if @offer.published
      @offer.published = false
    else
      @offer.published = true
    end
    @offer.save
  end

  def show
  end

  def wishlist
    @offers = current_user.find_voted_items.reject { |voted_item| voted_item.class != Offer }
  end

  def wish
    @offer.liked_by current_user
    respond_to do |format|
      format.html { redirect_to offer_path(@offer) }
      format.js
    end
  end

  def unwish
    @offer.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to offer_path(@offer) }
      format.js
    end
  end

  def map
    @offers = Offer.all
    authorize @offers

    @markers = Gmaps4rails.build_markers(@offers) do |offer, marker|
      marker.lat offer.user.latitude
      marker.lng offer.user.longitude
      marker.title offer.user.first_name
      marker.infowindow "
            <div class='text-center'>
              <img src='#{offer.user.picture.url(:thumb)}' class='img-nice' width='50'>
              <a href='#{offer_path(offer)}' class='nice-link info-link'>#{offer.nature}</a>
            </div>
            <a href='#{user_path(offer.user)}' class='nice-link info-link'>#{offer.user.first_name}</a>
            <p>#{offer.user.address}</p>
            <p>#{offer.one_price('€/heure', '€/semaine', '€/jour')}</p>"
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def offer_params
    params.require(:offer).permit(:type_of_offer, :nature, :description, :hourly_price, :daily_price, :weekly_price, :price, :picture, :public, :published, :guarantee)
  end

  def test_offer_info_and_redirect
    if @offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price'))
      if @offer.save
        if @offer.published
          @offer.send_new_offer_email
          @offer.create_activity :create, owner: current_user
        end
        redirect_to offer_path(@offer)
      else
        flash.now[:alert] = "Merci d'ajouter une description"
        render :new
      end
    else
      flash.now[:alert] = "Merci de renseigner un prix"
      render :new
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_client_actions.html.erb
<% if current_user.find_voted_items.include? @offer %>
  <%= link_to unwish_offer_path(@offer), class: "btn btn-success btn-wide btn-left", method: :put do %>
    <i class="fa fa-star"></i>&nbsp;&nbsp;&nbsp;&nbsp;<%= t('.unwish') %>
  <% end %>
<% else %>
  <%= link_to wish_offer_path(@offer), class: "btn btn-success btn-wide btn-left", method: :put do %>
    <i class="fa fa-star"></i>&nbsp;&nbsp;&nbsp;&nbsp;<%= t('.wish') %>
  <% end %>
<% end %>
<br>
<br>
<%= link_to new_offer_conversation_path(@offer), class: "btn btn-default btn-wide btn-left" do %>
  <i class="fa fa-envelope"></i>&nbsp;&nbsp;&nbsp;&nbsp;<%= t('.contact_owner') %>
<% end %>
<br>
<br>
<%= link_to new_offer_booking_path(@offer), class: "btn btn-primary btn-wide btn-left" do %>
  <i class="fa fa-check"></i>&nbsp;&nbsp;&nbsp;&nbsp;<%= t('.book') %>
<% end %>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <div class="form-group">
    <%= f.label :type_of_offer, t('.type'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :type_of_offer, [[t('.rent'), :rent], [t('.sell'), :sell], [t('.service'), :service]], {}, { class: "form-control", id: "type-select" } %>
    </div>
  </div>
  <div class="form-group hidden show-service" id="nature-select-service">
    <%= f.label :nature, t('.nature'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :nature, @natures[:service].sort,
                   { include_blank: true },
                   { class: "chosen-select", id: 'service' } %>
      <p class="small">
        <%= t('.suggest_service') %> <%= link_to new_user_conversation_path(User.find(1)) do %>
          <%= t('.here') %>
        <% end %>
      </p>
    </div>
  </div>
  <div class="form-group hidden show-sell" id="nature-select-sell">
    <%= f.label :nature, t('.nature'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nature, class: 'form-control', id: 'sell' %>
    </div>
  </div>
  <div class="form-group show-rent">
    <%= f.label :nature, t('.nature'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :nature, @natures[:rent].sort,
                   { include_blank: true },
                   { class: "chosen-select", id: 'rent' } %>
      <p class="small">
        <%= t('.suggest_rental') %> <%= link_to t('.here'), new_user_conversation_path(User.find(1)) %>
      </p>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, t('.description'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, required: true, class: "form-control" %>
      <p class="small">
        <%= t('.complete_description') %>
      </p>
    </div>
  </div>
  <div class="form-group service show-service hidden">
    <%= f.label :hourly_price, t('.price'), class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :hourly_price, min: 0, class: "form-control" %>
    </div>
    <div class="col-sm-5 padding-vertical-6">
      <%= t('.hourly_rate') %>
    </div>
  </div>
  <div class="form-group show-rent">
    <%= f.label :daily_price, t('.price'), class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :daily_price, min: 0, class: "form-control" %>
    </div>
    <div class="col-sm-5 padding-vertical-6">
      <%= t('.daily_rate') %>
    </div>
  </div>
  <div class="form-group show-rent">
    <%= f.label :weekly_price, "Prix", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :weekly_price, min: 0, class: "form-control" %>
    </div>
    <div class="col-sm-5 padding-vertical-6">
      <%= t('.weekly_rate') %>
    </div>
    <div class="col-sm-10 col-sm-offset-2">
      <p class="small"><%= t('.price_helper') %></p>
    </div>
  </div>
  <div class="form-group show-rent">
    <%= f.label :guarantee, t('.guarantee'), class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :guarantee, min: 0, class: "form-control" %>
    </div>
    <div class="col-sm-5 padding-vertical-6">
      <%= t('.currency') %>
    </div>
  </div>
  <div class="form-group show-sell hidden">
    <%= f.label :price, t('.price'), class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.number_field :price, min: 0, class: "form-control" %>
    </div>
    <div class="col-sm-5 padding-vertical-6">
      €
    </div>
  </div>
  <div class="form-group">
    <%= f.label :photo, t('.picture'), class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <ul class="list-unstyled list-inline margin-top-7 image-upload-trigger" id="image-upload-trigger">
        <li style="font-size: 26"><i class="fa fa-camera"></i></li>
        <li class=""><%= t('.upload', default: "Parcourir") %></li>
      </ul>
      <%= f.file_field :picture, class: "margin-top-6 hidden" %>
      <%= image_tag "", class: "img hidden", id: "target" %>
    </div>
  </div>
  <br>
  <div class="form-group margin-btm-none">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-10">
      <%= f.submit t('.save'), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#image-upload-trigger').on('click', function() {
        $('#offer_picture').click();
      })
    });
  <% end %>
<% end %>

app/views/offers/_offer_preview.html.erb
<div class="offer-stream-box">
  <div class="row">
    <div class="col-xs-1">
      <div class="img-nature-box">
        <%= image_tag "drill.png", class: "img img-nature" %>
      </div>
    </div>
    <div class="col-xs-9 padding-left-30">
      <h4 class="margin-none"><%= link_to offer.i18n_nature(params[:locale]), offer_path(offer), class: "offer-nature-link" %></h4>
      <p class="margin-top-10"><%= offer.description %> <%=link_to "Voir l'annonce complète", offer_path(offer) %></p>
      <ul class="list-unstyled list-inline">
        <li class="float-left">
          <%= link_to "#" do %>
            <i class="fa fa-camera"></i> Voir la photo
          <% end %>
        </li>
        <li class="float-left">
          <%= link_to "#" do %>
            <i class="fa fa-envelope"></i> Demande d'info
          <% end %>
        </li>
        <li class="float-left">
          <%= link_to "#" do %>
            <i class="fa fa-star"></i> Enregistrer
          <% end %>
        </li>
      </ul>
    </div>
    <div class="col-xs-2">
      <%= link_to "Modifier l'annonce", edit_offer_path(@offer), class: "btn btn-primary btn-wide" %>
      <% if @verif == 0 %>
        <br>
        <%= form_for @offer, method: :patch, url: offer_path(@offer)  do |f| %>
          <%= f.select :published, [["Publiée", true], ["Masquée", false]] %>
          <%= f.submit "Enregistrer" %>
        <% end %>
      <% else %>
        <br>
        <br>
        <%= link_to edit_user_path(current_user, anchor: "my-trust"), class: "btn btn-default btn-wide" do %>
          <%= pluralize(@verif, 'étape') %> pour publier
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/_owner_actions.html.erb
<%= link_to t('.edit') , edit_offer_path(@offer), class: "btn btn-primary btn-wide margin-btm-15" %>
<%= form_for @offer, remote: true, method: :patch, url: offer_path(@offer) do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <%= f.select :published, [[t('.hidden'), false], [t('.published'), true]], {}, { class: "form-control height-40 margin-btm-10", id: "hideOrPublish" } %>
    </div>
    <div class="text-center">
      <span class="badge small-badge margin-btm-10 <%= @offer.published ? '' : 'small-badge-off' %>"> </span>
    </div>
  </div>
<% end %>

app/views/offers/_wishlisted_offer.html.erb
<div class="offer-stream-box border-top" id="<%="offer_#{offer.id}"%>">
  <div class="row">
    <div class="col-xs-1 padding-right-none">
      <div class="img-nature-box">
        <%= image_tag "#{offer.type_of_offer == "sell" ? "sell" : offer.nature}.png", class: "img-nature" %>
      </div>
    </div>
    <div class="col-xs-9 padding-left-30 padding-right-none">
      <h5 class="margin-none"><%= link_to offer.i18n_nature(params[:locale]), offer_path(offer), class: "offer-nature-link neutralize" %></h5>
      <p class="margin-top-10"><%= offer.description %> <%=link_to t('.show_offer'), offer_path(offer), class: "neutralize" %></p>
    </div>
    <div class="col-xs-2 text-right padding-top-15 padding-left-none">
      <h4 class="margin-none text-right price">
        <%= offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')).match(/^.*[€$]/)[0] %>
      </h4>
      <% unless offer.type_of_offer == "sell" %>
        <p class="small">
          <%= offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')).match(/\/.*$/)[0] %>
        </p>
      <% end %>
    </div>
  </div>
  <% if offer.picture_file_name %>
    <div class="row">
      <div class="col-xs-12 text-center padding-vertical-10 hidden" id="<%="picture_#{offer.id}"%>">
        <%= link_to offer.picture.url(:large), class: "fancybox" do %>
          <%= image_tag(offer.picture.url(:medium), { class: "img-offer-pop" }) %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-1"></div>
      <div class="col-xs-11">
        <ul class="list-unstyled list-inline small">
          <% if offer.picture_file_name %>
            <li class="float-left">
              <a href="#" class="see-img hidden-xs" id="<%="show_picture_#{offer.id}"%>">
                <%= t('.show_pic') %>
              </a>
              <a href="#" class="see-img hidden hidden-xs" id="<%="hide_picture_#{offer.id}"%>">
                <%= t('.hide_pic') %>
              </a>
            </li>
          <% else %>
            <li class="float-left">
              <a href="#" class="disabled hidden-xs">
                <%= t('.show_pic') %>
              </a>
            </li>
          <% end %>
          <li class="float-right">
            <%= link_to new_offer_booking_path(offer), class: "neutralize", id: "offer_#{offer.id}" do %>
              <i class="fa fa-check"></i> <span class="hidden-xs"><%= t('.book') %></span>
            <% end %>
          </li>
          <li class="float-right">
            <%= link_to new_offer_conversation_path(offer), class: "neutralize", id: "offer_#{offer.id}" do %>
              <i class="fa fa-envelope"></i> <span class="hidden-xs"><%= t('.contact_owner') %></span>
            <% end %>
          </li>
          <li class="float-right">
            <% if current_user.find_voted_items.include? offer %>
              <%= link_to unwish_offer_path(offer), remote: true, class: "neutralize wished", id: "wishOffer_#{offer.id}", method: :put do %>
                <i class="fa fa-star"></i> <span class="hidden-xs"><%= t('.unwish') %></span>
              <% end %>
            <% else %>
              <%= link_to wish_offer_path(offer), remote: true, class: "neutralize", id: "wishOffer_#{offer.id}", method: :put do %>
                <i class="fa fa-star"></i> <span class="hidden-xs"><%= t('.wish') %></span>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/offers/mine.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="panel panel-default white-bg margin-top-15 padding-none" id="mine">
        <div class="panel-heading">
          <h4><%= t('.my_offers') %></h4>
        </div>
        <% if current_user.offers.size > 0 %>
          <div class="loader"> </div>
          <%= react_component "OfferList",
            render(template: 'offers/mine.json.jbuilder')
          %>
        <% else %>
          <div class="offer-stream-box border-top-221">
            <p><%= t('.no_offer') %></p>
            <p><%= link_to "Publier une annonce", new_offer_path %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= content_for :js do %>
  <% javascript_tag do %>
    mine()
  <% end %>
<% end %>

app/views/offers/unwish.js.erb
var wish = '<i class="fa fa-star"></i><i class="hidden-xs"> ' + '<%= t(".wish") %>' + '</i>'
$('#wishOffer_' + '<%= @offer.id %>').html(wish);
$('#wishOffer_' + '<%= @offer.id %>').removeClass('wished');
$('#wishOffer_' + '<%= @offer.id %>').css('text-decoration', 'none');
$('#wishOffer_' + '<%= @offer.id %>').attr('href', '<%= wish_offer_path(@offer) %>');

app/views/offers/update.js.erb
var flash = $('<%= j render "layouts/notices" %>').hide()
$('nav.navbar-wagon').prepend(flash.slideDown())
<% if @offer.published %>
  $('.small-badge').removeClass('small-badge-off')
<% else %>
  $('.small-badge').addClass('small-badge-off')
<% end %>
notices()

app/views/offers/wish.js.erb
var unwish = '<i class="fa fa-star"></i><i class="hidden-xs"> ' + '<%= t(".unwish") %>' + '</i>'
$('#wishOffer_' + '<%= @offer.id %>').html(unwish);
$('#wishOffer_' + '<%= @offer.id %>').addClass('wished');
$('#wishOffer_' + '<%= @offer.id %>').css('text-decoration', 'none');
$('#wishOffer_' + '<%= @offer.id %>').attr('href', '<%= unwish_offer_path(@offer) %>');