config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations", sessions: "sessions" }
  put "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post"
  patch "/activity/:id/like_activity", to: "posts#like_activity", as: "like_activity_post_2"
  put "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post"
  patch "/activity/:id/unlike_activity", to: "posts#unlike_activity", as: "unlike_activity_post_2"
  put "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity"
  patch "/activity/:id/comment_activity", to: "posts#update_activity", as: "activity_2"
  post 'bookings/:booking_id/reviews', to: "reviews#create", as: "booking_review"
  post 'bookings/:booking_id/conversations', to: "conversations#create_b", as: "booking_conversations"
  post 'users/:user_id/conversations', to: "conversations#create_u", as: "user_conversations"
  put 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review"
  patch 'bookings/:booking_id/reviews/:id', to: "reviews#update", as: "update_booking_review_2"
  put 'users/:id', to: "users#update", as: "user"
  patch 'users/:id', to: "users#update", as: "user_2"
  post 'offers/:offer_id/bookings', to: "bookings#create", as: 'offer_bookings'
  put 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking'
  patch 'offers/:offer_id/bookings/:id', to: "bookings#update", as: 'offer_booking_2'
  post 'offers/:offer_id/conversations', to: "conversations#create", as: 'offer_conversations'
  post 'offers/:offer_id/stripe_customers', to: "stripe_customers#create", as: "offer_stripe_customers"
  put 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation"
  patch 'conversations/:id/reply', to: "conversations#reply", as: "reply_conversation_2"
  put 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation"
  patch 'conversations/:id/reply_server', to: "conversations#reply_server", as: "reply_server_conversation_2"
  patch 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking"
  put 'bookings/:id/buy', to: "bookings#buy", as: "buy_booking_2"
  patch 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking"
  put 'bookings/:id/cancel', to: "bookings#cancel", as: "cancel_booking_2"
  scope '(:locale)', locale: /en/ do
    root to: "pages#home"
    get "/raclette", to: "pages#raclette"
    get "/legal", to: "pages#legal"
    get "/terms", to: "pages#terms"
    get "/sitemap", to:"pages#sitemap"
    get "/poster", to:"pages#poster"
    get "/early_birds_poster", to:"pages#early_birds_poster"
    get "/users/map", to: "users#map"
    get "/offers/map", to: "offers#map"
    resources :users, only: [:index, :show, :edit]
    resources :offers, except: :destroy do
      member do
        put :wish, to: "offers#wish"
        put :unwish, to: "offers#unwish"
        put :publish, to: "offers#publish"
        put :hide, to: "offers#hide"
      end
      resources :bookings, only: [:new, :edit, :show]
      resources :conversations, only: :new
      resources :stripe_customers, only: :new
    end
    resources :posts, only: [:index, :create, :update] do
      member do
        put :like, to: "posts#like"
        put :unlike, to: "posts#unlike"
      end
    end
    get 'bookings/:booking_id/reviews/new', to: "reviews#new", as: "new_booking_review"
    get 'bookings/:booking_id/conversations/new', to: "conversations#new_b", as: "new_booking_conversation"
    get 'users/:user_id/conversations/new', to: "conversations#new_u", as: "new_user_conversation"
    get 'bookings/:booking_id/reviews/:id/edit', to: "reviews#edit", as: "edit_booking_review"
    get 'reviews/:id', to: "reviews#show", as: "review"
    get "/mine", to: "offers#mine"
    get "/wishlist", to: "offers#wishlist"
    resources :conversations, only: [:index, :show]
  end
  resources :stripe_payments, only: [:new, :create]
end

app/models/post.rb
module PublicActivity
  module ORM
    module ActiveRecord
      class Activity < ::ActiveRecord::Base
        acts_as_votable
        has_many :activity_comments
      end
    end
  end
end
class Post < ActiveRecord::Base
  include PublicActivity::Common
  # tracked only: [:like, :like_activity, :update], owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_attached_file :picture,
    styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
      content_type: /\Aimage\/.*\z/

  validates_presence_of :user, :content
  acts_as_votable

  def send_lh_post_email
    PostMailer.lh_post(self).deliver
  end

  def send_post_email
    PostMailer.post(self).deliver
  end

  def send_like_email(user)
    PostMailer.like(self, user).deliver
  end
end

app/controllers/posts_controller.rb
require 'uri'
class PostsController < ApplicationController
  def index
    if current_user.latitude.nil?
      redirect_to edit_user_path(current_user)
      flash.keep[:alert] = t(".complete_profile")
    else
      @posts = current_user.posts_in_scope
      @post = Post.new
      if current_user.admin
        @comments = PublicActivity::Activity.order("created_at desc").where(key: "comment.update").group_by { |a| a.trackable.post }.values.map { |g| g.first }
        @other_activities = PublicActivity::Activity.order("created_at desc").where(key: ["offer.create", "user.update", "post.like"]).group_by(&:trackable_id).values.map { |g| g.first }
      else
        @comments = PublicActivity::Activity.order("created_at desc").where(owner: current_user.neighbors_lh_and_self).where(key: "comment.update").group_by { |a| a.trackable.post }.values.map { |g| g.first }
        @other_activities = PublicActivity::Activity.order("created_at desc").where(owner: current_user.neighbors_lh_and_self).where(key: ["offer.create", "user.update", "post.like"]).group_by(&:trackable_id).values.map { |g| g.first }
      end
      @activities = @comments + @other_activities
      @items = @posts + @activities
      @items = @items.sort_by(&:created_at).reverse
      @items = Kaminari.paginate_array(@items).page(params[:page]).per(15)
      respond_to do |format|
        format.html {}
        format.js
      end
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    url = URI.extract(@post.content, /https?.*/)
    if url.size > 0
      unless url.first.match(/https:\/\/www.lovely-hood.com\//)
        page = MetaInspector.new(url.first)
        @post.link_url = url.first
        @post.link_title = page.title
        @post.link_image = page.images.best
        @post.link_description = page.description
        @post.content = @post.content.split(url.first).join
        @post.content = "***" if @post.content == ""
      end
    end
    if @post.save
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
      if @post.user == User.find_by(first_name: "Lovely Hood")
        @post.send_lh_post_email
      else
        @post.send_post_email
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def update
    set_post
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      @comment.send_comment_email if (@post.user.comment_notif && @post.user != @comment.user)
      @comment.create_activity :update, owner: current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def update_activity
    set_activity
    @comment = ActivityComment.new(activity_comment_params)
    @comment.user = current_user
    @comment.activity_id = @activity.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def like
    set_post
    @post.liked_by current_user
    @post.send_like_email(current_user) if @post.user.like_notif
    @post.create_activity :like, owner: current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def unlike
    set_post
    @post.unliked_by current_user
    PublicActivity::Activity.find_by(owner: current_user, trackable: @post).destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def like_activity
    set_activity
    @activity.liked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def unlike_activity
    set_activity
    @activity.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_activity
    @activity = PublicActivity::Activity.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :picture)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def activity_comment_params
    params.require(:activity_comment).permit(:content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_activity.html.erb
<div class="panel panel-default white-bg margin-top-15 padding-none">
  <div class="panel-body border-btm">
    <div class="stick-down-target white-bg row" id="activity_<%= activity.id %>">
      <div class="col-xs-3 img-small-square margin-left-15 padding-none">
        <% if activity.owner.picture_file_name %>
          <%= image_tag(activity.owner.picture.url(:medium), { class: "img" }) %>
        <% else %>
          <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
        <% end %>
      </div>
      <div class="col-xs-9 padding-left-10">
        <%= render_activity activity %>
        <% if activity.trackable_type == "Post" %>
          <% unless activity.trackable.link_url %>
            <% if current_user.find_voted_items.include? PublicActivity::ORM::ActiveRecord::Activity.find(activity.id) %>
              <%= link_to t('.unlike'), unlike_activity_post_path(activity), method: :put, remote: true, class: "like-link", id: "unlike_activity_link_#{activity.id}" %>
            <% else %>
              <%= link_to t('.like'), like_activity_post_path(activity), method: :put, remote: true, class: "like-link", id: "like_activity_link_#{activity.id}" %>
            <% end %>
            <span class="like-link"> · </span>
            <%= link_to t('.comment'), "#", class: "comment-activity-link", id: "comment_post_activity_#{activity.id}" %>
          <% end %>
        <% else %>
          <% if current_user.find_voted_items.include? PublicActivity::ORM::ActiveRecord::Activity.find(activity.id) %>
            <%= link_to t('.unlike'), unlike_activity_post_path(activity), method: :put, remote: true, class: "like-link", id: "unlike_activity_link_#{activity.id}" %>
          <% else %>
            <%= link_to t('.like'), like_activity_post_path(activity), method: :put, remote: true, class: "like-link", id: "like_activity_link_#{activity.id}" %>
          <% end %>
          <span class="like-link"> · </span>
          <%= link_to t('.comment'), "#", class: "comment-activity-link", id: "comment_post_activity_#{activity.id}" %>
        <% end %>
      </div>
    </div>
  </div>
  <div id="comments-stream-activity-<%= activity.id %>">
    <% unless activity.get_likes.size == 0 %>
      <%= render 'likes', post: activity %>
    <% end %>
    <% activity.activity_comments.each do |comment| %>
      <%= render 'comment', comment: comment %>
    <% end %>
  </div>
  <div class="panel-footer padding-top-15 padding-btm-15 border-top-none" id="panel-footer-activities">
    <%= form_for [activity, ActivityComment.new], method: :put, url: activity_path(activity), remote: true, autocomplete: "off" do |f| %>
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-2 img-mini-square padding-none margin-left-none">
            <% if current_user.picture_file_name %>
              <%= image_tag(current_user.picture.url(:medium), { class: "img" }) %>
            <% else %>
              <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
            <% end %>
          </div>
          <div class="col-xs-10 padding-left-10 padding-right-none width-92 js-target">
            <div class="form-group margin-btm-none total-width">
              <%= f.text_field :content, autocomplete: "off", placeholder: t('.placeholder'), class: "form-control height-32 font-size-12", id: "comment_content_post_activity_#{activity.id}" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_comment.html.erb
<div class="panel-footer padding-top-15 padding-btm-none border-top-none" id="panel-footer-posts">
  <div class="row">
    <div class="col-xs-12">
      <div class="col-xs-2 img-mini-square padding-none margin-left-none">
        <% if comment.user.picture_file_name %>
          <%= image_tag(comment.user.picture.url(:medium), { class: "img" }) %>
        <% else %>
          <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
        <% end %>
      </div>
      <div class="col-xs-10 padding-left-10">
        <div class="font-size-12">
          <ul class="margin-none list-unstyled list-inline">
            <li class="padding-left-none">
              <%= link_to comment.user.first_name, user_path(comment.user), class: "offer-nature-link montserrat" %>
            </li>
            <li class="padding-left-none gray-lighter font-size-12">
              <%= (((Time.now - comment.created_at < 86400) && Date.today.day == comment.created_at.day) ? l(comment.created_at, format: :short)[-5..-1] : (Time.now - comment.created_at < 86400 ? (t('.yesterday') + ' ' + l(comment.created_at, format: :short)[-5..-1]) : l(comment.created_at, format: :short))) %>
            </li>
          </ul>
          <%= simple_format comment.content, class: "margin-btm-none" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes-popup.html.erb
<ul class="likes-popup">
  <% post.get_likes.each do |liker| %>
    <li><%= liker.voter.first_name %></li>
  <% end %>
</ul>

app/views/posts/_meta.html.erb
<%= link_to post.link_url, target: "_blank" do %>
  <div class="row margin-top-15">
    <%= image_tag post.link_image, class: "img img-meta" %>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h4><%= post.link_title %></h4>
      <%= simple_format post.link_description, class: "font-normal margin-btm-15" %>
    </div>
  </div>
<% end %>

app/views/posts/_offer.html.erb
<% if offer.published %>
  <%= link_to offer_path(offer), target: "_blank" do %>
    <div class="panel panel-default white-bg margin-top-15 margin-btm-15 padding-none box-in-post">
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-3 col-sm-2">
            <div class="img-nature-box">
              <%= image_tag "#{offer.type_of_offer == "sell" ? "sell" : offer.nature}.png", class: "img-nature" %>
            </div>
          </div>
          <div class="col-xs-9 col-sm-10">
            <ul class="margin-none list-unstyled list-inline">
              <li class="padding-left-none offer-nature-link montserrat"><%= offer.i18n_nature(params[:locale]) %></li>
              <li class="padding-left-none font-normal"><%= offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')) ? offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')) : "" %></li>
            </ul>
            <p class="margin-top-10 font-normal hidden-xs"><%= offer.description.size > 50 ? offer.description[0..49] + "..." : offer.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="panel panel-default white-bg margin-top-15 margin-btm-15 padding-none box-in-post">
    <div class="panel-body">
      <div class="row">
        <div class="col-xs-3 col-sm-2">
          <div class="img-nature-box">
            <%= image_tag "#{offer.type_of_offer == "sell" ? "sell" : offer.nature}.png", class: "img-nature" %>
          </div>
        </div>
        <div class="col-xs-9 col-sm-10">
          <ul class="margin-none list-unstyled list-inline">
            <li class="padding-left-none"><b><%= offer.i18n_nature(params[:locale]) %></b></li>
            <li class="padding-left-none font-normal"><%= offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')) ? offer.one_price(t('.hourly_price'), t('.weekly_price'), t('.daily_price')) : "" %></li>
          </ul>
          <p class="margin-top-10 font-normal hidden-xs"><%= offer.description.size > 50 ? offer.description[0..49] + "..." : offer.description %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default white-bg margin-top-15 padding-none">
  <div class="panel-body padding-top-none border-btm">
    <div class="stick-down-target white-bg row" id="post_<%= post.id %>">
      <div class="message-content margin-top-15">
        <div class="col-xs-3 img-small-square margin-left-15 padding-none">
          <% if post.user.picture_file_name %>
            <%= image_tag(post.user.picture.url(:medium), { class: "img" }) %>
          <% else %>
            <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
          <% end %>
        </div>
        <div class="col-xs-9 padding-left-10">
          <ul class="margin-none list-unstyled list-inline">
            <li class="padding-left-none">
              <%= link_to post.user.first_name, user_path(post.user), class: "offer-nature-link montserrat" %>
            </li>
            <li class="padding-left-none gray-lighter font-size-12">
              <%= (((Time.now - post.created_at < 86400) && Date.today.day == post.created_at.day) ? l(post.created_at, format: :short)[-5..-1] : (Time.now - post.created_at < 86400 ? t('.yesterday') + ' ' + l(post.created_at, format: :short)[-5..-1] : l(post.created_at, format: :short))) %>
            </li>
          </ul>
          <%= simple_format post.content, class: "margin-btm-none box-in-post" unless post.content == "***" %>
          <% if post.picture_file_name %>
        </div>
        <div class="col-xs-12">
          <div class="row margin-top-15 margin-btm-13">
            <div class="col-xs-12">
              <%= image_tag post.picture.url(:large), class: "img img-meta" %>
              <div class="col-xs-12 total-width border-btm-light padding-none margin-top-15">
              </div>
            </div>
          </div>
          <% if current_user.find_voted_items.include? post %>
            <%= link_to "Je n'aime plus", unlike_post_path(post), method: :put, remote: true, class: "like-link", id: "unlike_link_#{post.id}" %>
          <% else %>
            <%= link_to "J'aime", like_post_path(post), method: :put, remote: true, class: "like-link", id: "like_link_#{post.id}" %>
          <% end %>
          <span class="like-link"> · </span>
          <%= link_to "Commenter", "#", class: "comment-link", id: "comment_post_#{post.id}" %>
        </div>
          <% elsif post.link_url %>
        </div>
        <div class="col-xs-12">
              <%= render "meta", post: post %>
              <% if current_user.find_voted_items.include? post %>
                <%= link_to t('.unlike'), unlike_post_path(post), method: :put, remote: true, class: "like-link", id: "unlike_link_#{post.id}" %>
              <% else %>
                <%= link_to t('.like'), like_post_path(post), method: :put, remote: true, class: "like-link", id: "like_link_#{post.id}" %>
              <% end %>
              <span class="like-link"> · </span>
              <%= link_to t('.comment'), "#", class: "comment-link", id: "comment_post_#{post.id}" %>
        </div>
          <% else %>
            <% if current_user.find_voted_items.include? post %>
              <%= link_to t('.unlike'), unlike_post_path(post), method: :put, remote: true, class: "like-link", id: "unlike_link_#{post.id}" %>
            <% else %>
              <%= link_to t('.like'), like_post_path(post), method: :put, remote: true, class: "like-link", id: "like_link_#{post.id}" %>
            <% end %>
            <span class="like-link"> · </span>
            <%= link_to t('.comment'), "#", class: "comment-link", id: "comment_post_#{post.id}" %>
        </div>
          <% end %>
      </div>
    </div>
  </div>
  <div id="comments-stream-post-<%= post.id %>">
    <% unless post.get_likes.size == 0 %>
      <%= render 'likes', post: post %>
    <% end %>
    <% post.comments.each do |comment| %>
      <%= render 'comment', comment: comment %>
    <% end %>
  </div>
  <div class="panel-footer padding-top-15 padding-btm-15 border-top-none" id="panel-footer-posts">
    <%= form_for [post, Comment.new], method: :put, url: post_path(post), remote: true, autocomplete: "off" do |f| %>
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-2 img-mini-square padding-none margin-left-none">
            <% if current_user.picture_file_name %>
              <%= image_tag(current_user.picture.url(:medium), { class: "img" }) %>
            <% else %>
              <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
            <% end %>
          </div>
          <div class="col-xs-10 padding-left-10 padding-right-none width-92 js-target">
            <div class="form-group margin-btm-none total-width">
              <%= f.text_field :content, autocomplete: "off", placeholder: t('.placeholder'), class: "form-control height-32 font-size-12", id: "comment_content_post_#{post.id}" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>
<%= content_for(:description) do %>
  <%= t('.description') %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <div class="panel panel-default white-bg margin-top-15 padding-none">
        <%= form_for @post, html: { multipart: true }, method: :post, url: posts_path, remote: true, authenticity_token: true do |f| %>
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-12">
                <div class="col-xs-2 img-small-square padding-none margin-left-none">
                  <% if current_user.picture_file_name %>
                    <%= image_tag(current_user.picture.url(:medium), { class: "img" }) %>
                  <% else %>
                    <%= image_tag "user_pic-60.png", class: "img logo-small bg-color" %>
                  <% end %>
                </div>
                <div class="col-xs-10 padding-left-10 js-other-target">
                  <div class="form-group margin-btm-none">
                    <%= f.text_area :content, placeholder: t('.placeholder'), style: "resize: none", class: "form-control height-42 padding-top-none padding-left-none border-none box-in-post" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="panel-footer" id="panel-footer-posts">
            <%= f.file_field :picture, class: "hidden" %>
            <ul class="list-unstyled list-inline margin-btm-none">
              <li id="camera"><i class="fa fa-camera"></i></li>
              <li class="pic-path" id="placeholder"></li>
              <li class="pic-path hidden" id="check"><i class="fa fa-check"></i></li>
              <li class="pull-right"><%= f.submit t('.post'), class: "btn btn-post pull-right" %></li>
            </ul>
          </div>
        <% end %>
      </div>
      <div id="posts-stream">
        <% @items.each do |item| %>
          <% if item.class == Post %>
            <%= render "post", post: item %>
          <% else %>
            <%# unless item.trackable_type == "Offer" && item.trackable.try(:published) == false %>
              <%# render "activity", activity: item if (item.owner && item.trackable) %>
            <%# end %>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-xs-12 text-center">
          <%= paginate @items %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= content_for :js do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      // $('#share').removeClass('hidden')
      postsIndex()
      setTimeout(function() {
        postsPicMaxSize()
      }, 400)
      $(window).on('scroll', function() {
        var more_posts_url = $('.next a').attr('href')
        if(more_posts_url && $(window).scrollTop() > $(document).height() - $(window).height() - 60) {
          $('.pagination').html('<img src="<%= asset_url('facebook.gif') %>" alt="Loading..." title="Loading..." />')
          $.ajax({
            type: 'GET',
            url: more_posts_url,
            dataType: 'script',
            success: function() {
              postsIndex()
              setTimeout(function() {
                postsPicMaxSize()
              }, 400)
            }
          })
        }
        return false
      })
    })
  <% end %>
<% end %>

app/views/posts/like.js.erb
<% if @post.get_likes.size > 1 %>
  $('#like_link_' + <%= @post.id %>).html("<%= t('.unlike') %>")
  $('#like_link_' + <%= @post.id %>).attr("href", "<%= unlike_post_path(@post) %>")
  $('#like_link_' + <%= @post.id %>).attr("id", "unlike_link_" + <%= @post.id %>)
  $('#likes_' + <%= @post.id %>).slideUp(function() {
    var like_infos = $("<%= j render 'likes', post: @post %>").hide();
    $('#comments-stream-post-' + <%= @post.id %>).prepend(like_infos);
    like_infos.slideDown();
  })
<% else %>
  $('#like_link_' + <%= @post.id %>).html("<%= t('.unlike') %>")
  $('#like_link_' + <%= @post.id %>).attr("href", "<%= unlike_post_path(@post) %>")
  $('#like_link_' + <%= @post.id %>).attr("id", "unlike_link_" + <%= @post.id %>)
  var like_infos = $("<%= j render 'likes', post: @post %>").hide();
  $('#comments-stream-post-' + <%= @post.id %>).prepend(like_infos);
  like_infos.slideDown();
<% end %>

app/views/posts/like_activity.js.erb
<% if @activity.get_likes.size > 1 %>
  $('#like_activity_link_' + <%= @activity.id %>).html("<%= t('.unlike') %>")
  $('#like_activity_link_' + <%= @activity.id %>).attr("href", "<%= unlike_activity_post_path(@activity) %>")
  $('#like_activity_link_' + <%= @activity.id %>).attr("id", "unlike_activity_link_" + <%= @activity.id %>)
  $('#likes_activity_' + <%= @activity.id %>).slideUp(function() {
    var like_infos = $("<%= j render 'likes', post: @activity %>").hide();
    $('#comments-stream-activity-' + <%= @activity.id %>).prepend(like_infos);
    like_infos.slideDown();
  })
<% else %>
  $('#like_activity_link_' + <%= @activity.id %>).html("<%= t('.unlike') %>")
  $('#like_activity_link_' + <%= @activity.id %>).attr("href", "<%= unlike_activity_post_path(@activity) %>")
  $('#like_activity_link_' + <%= @activity.id %>).attr("id", "unlike_activity_link_" + <%= @activity.id %>)
  var like_infos = $("<%= j render 'likes', post: @activity %>").hide();
  $('#comments-stream-activity-' + <%= @activity.id %>).prepend(like_infos);
  like_infos.slideDown();
<% end %>

app/views/posts/unlike.js.erb
<% if @post.get_likes.size == 0 %>
  $('#unlike_link_' + <%= @post.id %>).html("<%= t('.like') %>")
  $('#unlike_link_' + <%= @post.id %>).attr("href", "<%= like_post_path(@post) %>")
  $('#unlike_link_' + <%= @post.id %>).attr("id", "like_link_" + <%= @post.id %>)
  $('#likes_' + <%= @post.id %>).slideUp()
<% else %>
  $('#unlike_link_' + <%= @post.id %>).html("<%= t('.like') %>")
  $('#unlike_link_' + <%= @post.id %>).attr("href", "<%= like_post_path(@post) %>")
  $('#unlike_link_' + <%= @post.id %>).attr("id", "like_link_" + <%= @post.id %>)
  $('#likes_' + <%= @post.id %>).slideUp(function() {
    var like_infos = $("<%= j render 'likes', post: @post %>").hide();
    $('#comments-stream-post-' + <%= @post.id %>).prepend(like_infos);
    like_infos.slideDown();
  })
<% end %>